### PR TITLE
retrieve binary.csv with open-uri

### PR DESCRIPTION
**Pull request by kozo2**

### CODE REVIEW

**Comment by v0dro** [comment]
Did you try running this notebook? Are you sure it works?

Also, could you please squash this into a single commit?

**Comment by kozo2** [comment]
Yes, but this notebook fails like this
https://gist.github.com/kozo2/f2a391a6d65ed76ab5a8

And I squashed this into a single commit.

**Comment by v0dro** [comment]
Might be something with the latest daru. Thanks for reporting. Will check it out.

**Comment by kozo2** [comment]
And it seems to me that [this docker image](https://hub.docker.com/r/minad/sciruby-notebooks/) does not support docker toolbox users.
I tried to modify and rebuild this image, but ```gem install sciruby-full``` fails because of dependency error.
So I created new automated build for iruby notebook environment.
https://github.com/kozo2/iruby-notebook

Please use this container to reproduce this error.

**Comment by v0dro** [comment]
Bug fixed. Check the notebook again please.

**Comment by kozo2** [comment]
Thank you.
It works well now.

**Pull request merged**
