### PR TITLE
Update sort

### PR DESCRIPTION
**Pull request by lokeshh**
Update notebooks due to changes in Dataframe#sort.

### CODE REVIEW

**Comment by lokeshh** [comment]
This is all I guess there's necessary to reflect the changes made in DataFrame#sort but I want to run all the notebooks once and verify if every thing is working fine or not. 

Further I am also thinking about adding more examples to expose advance features of sorting in the notebook. I am not sure whether it be good idea or not because one can always look to the documentation and it would make the notebook long and maybe we want to show the basic functionalities. I don't know. What's your opinion?

**Comment by v0dro** [comment]
Put the advanced features in the notebook and the documentation too so that users can see everything at a glance irrespective of what material they're referring to.

**Comment by v0dro** [comment]
I'm just going to try running those on  my computer.

**Comment by v0dro** [comment]
The notebooks run fine on my PC. I have a hunch that the problem lies in the fact that you might have installed rvm as root (given that all your paths start from `/usr/local/...`. Could you try with a fresh rvm install without root? Maybe there's some privilege issue?

**Comment by lokeshh** [comment]
I tried. It's the same. The error is now:

```ruby
Gem::ConflictError: Unable to activate statsample-2.0.1, because spreadsheet-1.1.1 conflicts with spreadsheet (~> 1.0.3)
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts'
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:198:in `rescue in try_activate'
```

**Comment by lokeshh** [comment]
I also get following output while running `iruby` but it works inspite of the error or whatever it is:

```ruby
Could not load bundler: Could not locate Gemfile or .bundle/ directory
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console`... continue in 5 sec. Press Ctrl-C to quit now.
W, [2016-03-11T13:10:15.619117 #52944]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:163:in `rescue in root'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:159:in `root'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:71:in `bundle_path'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:401:in `configure_gem_home_and_path'
```

**Comment by lokeshh** [comment]
I think the issue with gnuplotrb is resolved. Though I am getting another error message but I don't think this has to do with gnuplotrb.

```ruby
NoMethodError: undefined method `keys' for nil:NilClass
```

It's weird why `statsample` isn't working in notebook but working with iruby.

**Comment by lokeshh** [comment]
I think the issue is resolved now. Earlier 'statsample' was working with irb but not with iruby. Now it's not working with both.

**Comment by v0dro** [comment]
I think you should activate the gems with the `gem` method first.

```
gem 'statsample'
```

**Comment by v0dro** [comment]
That statsample error is being caused because the latest daru uses `spreadsheet` 1.1.1 and statsample uses an older version. I have pushed changes to the master of [Sciruby/statsample](https://github.com/sciruby/statsample), but the maintainers are yet to release a new version of the gem. Until then, you can use statsample from github directly.

**Comment by lokeshh** [comment]
Thanks. Statsample issue if fixed now. Just a couple of things are left to take care of then we are done:

- A weird output displays on the first cell and plots do not work no matter what because the code which is being displayed is supposed to be executed not displayed.
image
([Click here](http://www.zimagez.com/zimage/screenshot-03152016-103842pm.php) to see the image)
- Getting `NoMethodError: undefined method `keys' for nil:NilClass`with gnuplotrb

**Comment by v0dro** [comment]
That output is from nyaplot. It can be silenced by putting a lone print statement after the `require 'daru'`.

**Comment by lokeshh** [comment]
I have got a feeling that this output shouldn't be displayed. Because it doesn't display in nbviewer and plotting works fine there. I ran all the cells and then ran that modified notebook in nbviewer and plotting functionality also stopped there. My running all the cells is disrupting the plotting functionality. So, maybe something is wrong with new daru or nyaplot or ipython notebook or something else I don't know yet.

**Comment by lokeshh** [comment]
I've added additional examples and modified sort wherever necessary. The other task which was to run all the notebooks and verify they are running properly may take some more time and I think it's better to do it in another PR.

In this PR, I have done the following:
- Add additional examples to express advance functions of DataFrame#sort
- Saved required CSV's files in a folder Data to save the user from downloading the files separately in order to run the notebook.

I haven't touched any other notebook other than Usage of DataFrame because it would probably distort the plotting functionality.

**Comment by v0dro** [comment]
Can you try using Chrome?

Also, is this ready for merge?

**Comment by lokeshh** [comment]
It's the same with chrome. I've already tried.

Yes it's ready to be merged. Does nyaplot work when you run the notebook on
your computer?

**Comment by v0dro** [comment]
Yeah it does! Alternatively you can try using gnuplotrb for future plotting. It's pretty easy to use and has more features in many respects.

**Comment by lokeshh** [comment]
Do both gnuplotrb and nyaplot only work in iRuby or would they also work in IRB?

**Comment by v0dro** [comment]
I think only in iRuby. You'll need to export to an SVG file and open it separately in order to view them from irb.

**Comment by lokeshh** [comment]
nyaplot had the functionality to write to html in irb. I did that and when I opened the html file to which it exported the plot, I got a blank html with title as "Nyaplot". This confirms the problem's not with iRuby. Did you ran the notebooks with the latest gems releases?

**Comment by lokeshh** [comment]
Gnuplotrb is working fine for me except for [this](https://github.com/SciRuby/gnuplotrb/issues/4).

**Comment by v0dro** [comment]
I've never tried working with nyaplot on irb. If that is the case it should be a nyaplot issue.

**Comment by lokeshh** [comment]
Hurray! This patch domitry/nyaplot#67 fixes everything. Now plotting is working fine for me. I will update all the notebooks now.

**Pull request merged**
