### PR TITLE
retrieve music_data.tsv with open-uri

### PR DESCRIPTION
**Pull request by kozo2**

### CODE REVIEW

**Comment by v0dro** [comment]
Again, squash to a single commit.

**Comment by kozo2** [comment]
squashed,
and this notebook also fails like this
https://gist.github.com/kozo2/1794d62faf0b4db62bcf

**Comment by v0dro** [comment]
ok its been fixed.

**Comment by kozo2** [comment]
Sorry, it seems that ```Finding and plotting the most heard artists on last fm.ipynb``` still fails like cell[8]

https://gist.github.com/kozo2/cfc5b7606cbfa7e8b5f4

**Comment by v0dro** [comment]
The error does not seem to be related to daru. It works fine on my computer. Looks like an iruby encoding issue.

Could you please try running the code on the command line and see if it still gives the error?

**Comment by kozo2** [comment]
I tried running the code on the command line.
Certainly it works fine on the command line.
I will submit this issue to iruby.
Thank you.

**Pull request merged**
