### PR TITLE
Added notebooks for symengine

### PR DESCRIPTION
**Pull request by abinashmeher999**
@v0dro Could you please review this?

### CODE REVIEW

**Comment by minad** [comment]
How can this be used if there is no gem named symengine? Please create a gem and add it also to the list of sciruby gems https://github.com/SciRuby/sciruby/blob/master/gems.yml

**Comment by abinashmeher999** [comment]
Thanks. I will add it to the list. Is there somewhere where I can specify the custom build instructions? Currently I use the following instructions with the repo [sympy/symengine](https://github.com/sympy/symengine).
> # Steps to compile the extensions
   -  Install bundler by gem install bundler
   -  Change directory to src/ruby, cd symengine/ruby
   -  Execute bundle install this will install the gems required
   - Change to root directory, cd ../..
   - Build symengine with Ruby by adding the flag, cmake -DWITH_RUBY=yes .
   - Then cd to symengine/ruby again, cd symengine/ruby
   - Build the gem, gem build symengine.gemspec
   - Install the gem, gem install symengine-0.0.0.pre.gem

Or do I have to have the gem on RubyGems.org to add to the list of sciruby gems?

**Comment by minad** [comment]
the gem must be on rubygems.org

**Comment by v0dro** [comment]
@abinashmeher999 create a gem with your instructions and see if it just installs.

If not you might have to write some script that automates the above procedure.

**Comment by abinashmeher999** [comment]
@v0dro I was doing
```
gem build symengine.gemspec
gem install symengine-0.0.0.gem
```
to build and install the gem locally
What do want me to do after that? Send a PR to sciruby repo with the gem available in the repo itself? That might work because when we will perform a `bundle install` it might detect that an offline copy is available and get installed with the other gems. Will this work?

**Comment by v0dro** [comment]
1. Create a proper version for your gem (I think `0.0.1` should do for now).
2. Write a nice gemspec pointing out the source code and description etc.
3. Publish the gem to rubygems.org.

The problem with your current implementation is that getting started with your gem is tough. One should just be able to do `gem install symengine` and everything should work fine. That would actually make your code useful to people and your project worthwhile.

No need to send a PR anywhere. The code is fine wherever it is. It should just be easily downloadable and installable.

**Comment by v0dro** [comment]
@abinashmeher999 does the gem you've uploaded on rubygems work as expected after `gem install symengine`?

**Comment by v0dro** [comment]
I tried it out just now and I get a LoadError:

```
➜  ~  gem install symengine
Fetching: symengine-0.0.1.gem (100%)
Successfully installed symengine-0.0.1
Parsing documentation for symengine-0.0.1
Installing ri documentation for symengine-0.0.1
Done installing documentation for symengine after 0 seconds
1 gem installed
➜  ~  pry
[1] pry(main)> require 'symengine'
LoadError: /home/sameer/.rvm/gems/ruby-2.2.1/gems/symengine-0.0.1/lib/symengine/symengine.so: wrong ELF class: ELFCLASS64 - /home/sameer/.rvm/gems/ruby-2.2.1/gems/symengine-0.0.1/lib/symengine/symengine.so
from /home/sameer/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

```
Please look into this. I have a hunch its happening because the original CSymPy code is not being compiled when doing `gem install`.

You might have to write a script for first installing CSymPy before the gem is actually installed.

**Comment by abinashmeher999** [comment]
It doesn't work as of now. We are working on packaging the gem.

Yes, the reason is that the original SymEngine (previously called CSymPy)
library needs to be installed before the extensions are built.

**Comment by v0dro** [comment]
Has symengine been packaged as a gem? Can I use this now?

**Comment by abinashmeher999** [comment]
Yes, it has. But the user also needs to have the SymEngine C++ library
installed to use this. The gem provides only the wrappers. Will this affect
if the gem is included?

*Regards,*

*Abinash Meher*

**Comment by v0dro** [comment]
Only wrappers is fine. I just want to make sure if `gem install symengine` will work when the SymEngine C++ library is installed.

Could you make a note of that in the notebook?

**Comment by abinashmeher999** [comment]
@v0dro Done. Is it ok, now?

**Comment by abinashmeher999** [comment]
I guess [this](https://github.com/SciRuby/sciruby/blob/master/gems.yml#L402) needs to be updated for version 0.0.2.

**Pull request merged**
