### PR TITLE
Update notebooks

### PR DESCRIPTION
**Pull request by lokeshh**
Now the plotting functionality is working fine, this PR will update the notebooks using the latest gems.

### CODE REVIEW

**Comment by lokeshh** [comment]
@v0dro Where can I get 'sales-funnel.csv' which is used in 8th cell of [this](https://github.com/SciRuby/sciruby-notebooks/blob/master/Data%20Analysis/Grouping%2C%20Splitting%20and%20Pivoting.ipynb) notebook.

**Comment by v0dro** [comment]
https://github.com/v0dro/daru/blob/master/spec/fixtures/sales-funnel.csv

**Comment by lokeshh** [comment]
Thanks.

One last thing, cell 2 was producing errors. I changed 
```ruby
multi_index = Daru::MultiIndex.new(tuples)
```
to
```ruby
multi_index = Daru::MultiIndex.from_tuples(tuples)
```
It's working fine but cell 9 is giving error 
```ruby
sales.pivot_table index: [:Manager, :Rep]
ArgumentError: Vector Manager does not exist
```
Any idea regarding this?

**Comment by v0dro** [comment]
Can you trying changing it to `sales.pivot_table index: ['Manager', 'Rep']`?

**Comment by lokeshh** [comment]
Great. It worked. I'm updating other notebooks as well beside Data Analysis. I hope that's not a problem.

**Comment by v0dro** [comment]
Sure. Go ahead!

**Comment by lokeshh** [comment]
Running [this notebook](https://github.com/SciRuby/sciruby-notebooks/blob/master/Statistics/Polychoric%20Correlation.ipynb) gave me the error `LoadError: cannot load such file -- statsample/bivariate/polychoric`. 
I installed the `statsample-bivariate-extensino` via `gem install statsample-bivariate-extension`. It's still giving the same error. I tried running it in IRB, still the same error.
I went to the directory it can't find but it's there:
```ruby
(venv) lokeshh:~/.rvm/gems/ruby-2.2.1/gems/statsample-bivariate-extension-1.2.0/lib/statsample/bivariate $ ls
extension_version.rb  polychoric/  polychoric.rb  tetrachoric.rb
```

**Comment by v0dro** [comment]
Try uninstalling statsample and then install statsample-bivariate-extension. I think it happened because your installation of statsample failed to activate the gem.

**Comment by lokeshh** [comment]
Didn't worked. Here's what I did: https://gist.github.com/lokeshh/68581abf3cd2a74bea92

**Comment by lokeshh** [comment]
[This notebook](https://github.com/SciRuby/sciruby-notebooks/blob/master/Visualization/Boxplot%20with%20daru%20and%20statsample.ipynb) uses `a.push(2)` where 'a' is a Daru::Vector. This function `push` accepts two arguments, one new element to push and it's index. Since there was only one argument, it was raising as exception. I changed it to `a.push(2, a.length)`. It's working fine now. Thought I should let you know in case you have something else to suggest.

**Comment by v0dro** [comment]
Alright. Is this PR done? I'll look into the statsample issue soon. I recall making it work somehow...

**Comment by lokeshh** [comment]
Yep it's ready, all the notebooks are updated and running now except the statsample issue.

**Comment by v0dro** [comment]
What did you update in the getting started notebook? Couldn't see any changes.

**Comment by lokeshh** [comment]
Nothing. By update I just meant updating the output so that notebooks reflect the working of latest gems. I have ran all the notebooks and committed them irrespective of whether their output differs or not. Another motivation I did so because they hadn't been updated in a long time. As for notebooks with nyaplot involved, the updated notebooks now render plots correctly when viewed on nbviewer. One exception is getting_started notebook though. It's still not getting rendered properly on nbviewer.

**Comment by v0dro** [comment]
Alright. I think they were also written with iPython 2, and not Jupyter, so that's also updated now. I'll merge when you're ready.

**Comment by lokeshh** [comment]
Mysteriously changing "## Nyaplot" to "Nyaplot" made two nyaplot plots rendered properly.

Anyway, I've verified every notebook I've edited so far, is rendering complete and properly on nbviewer. This is ready to be merged.

**Pull request merged**
